version: "3.9"

services:
  monitor:
    build: monitor
    volumes:
      - data-volume:/workdir
    networks:
      - monredis

  generador:
    build: generador
    volumes:
      - data-volume:/workdir

  redis:
    image: "redis:alpine"
    networks:
      - monredis

volumes:
  data-volume:

networks:
  monredis: 
