version: "2"

services:
  monitor:
    build: monitor
    volumes:
      - data-volume:/workdir
  generador:
    build: generador
    volumes:
      - data-volume:/workdir

  redis:
    image: "redis:alpine"

volumes:
  data-volume:
   
