version: "3.9"

services:
  monitor:
    build: monitor
    command: python3 /myscript/monitor_eventos.py /workdir
    volumes:
      - data-volume:/workdir
  generador:
    build: generador
    volumes:
      - data-volume:/workdir

volumes:
  data-volume:
   
